### ISSUE TITLE
Support repetition?

### ISSUE THREAD

**Issue by polarathene** [jeremysalwen/rust-permutations#1]
It looks like this only allows permutations of n! where the values cannot repeat? eg `[0, 1, 2, 3]` can't create the permutation of `[1, 3, 2, 3]`. I've come across another permutation crate that seems to provide this, thought I'd mention it :)

**Comment by jeremysalwen** [comment]
I don't think I am going to add support for this, as it is qualitatively different that permutations, and requires additional machinery on the backend to support it.

**Comment by polarathene** [comment]
No worries. I ended up making my own solution in a few lines that does it. 26^5 permutations in about 40ms on a fixed Array or 500ms with a dynamic sized Vec.
