### ISSUE TITLE
Worse performance than "sorting" by indexing 

### ISSUE THREAD

**Issue by raui100** [jeremysalwen/rust-permutations#11]
Hello :) I'm building an image parser and I have to sort the values in an  vector `(img: Vec<u8>)` according to some `indices: Vec<usize>` that I calculate beforehand. 
The vector is pretty large and I had been quite happy, that this library provides a solution that works without reallocating. However simply remapping the indices is ~5 times faster than swapping in place and ~3.5 times faster than swapping with a new allocation.
I just wanted to ask if I'm doing something wrong because this performance difference strikes me as odd. There are about a thousand chunks that are being reordered in the same way. The code I use is below. Thanks in advance!

Cheers, Raui
<details>
<summary>Code</summary>

```rust
fn reorder_by_mapping(img: Vec<u8>, indices: Vec<usize>, chunk_size: usize) -> Vec<u8>{
    img.chunks_exact(chunk_size)
        .flat_map(|chunk| indices.iter().map(|ind| chunk[*ind]))
        .collect()
}

fn reorder_by_perm(img: Vec<u8>, indices: Vec<usize>, chunk_size: usize) -> Vec<u8>{
    let permutations = permutation::sort_unstable(&indices);  // All unique
    img.chunks_exact(chunk_size)
        .flat_map(|chunk| permutations.apply_slice(chunk))
        .collect()
}

fn reorder_by_perm_mut(mut img: Vec<u8>, indices: Vec<usize>, chunk_size: usize) -> Vec<u8>{
    let mut permutations = permutation::sort_unstable(&indices);  // All unique
    for chunk in img.chunks_exact_mut(chunk_size) {
        permutations.apply_slice_in_place(chunk)
    }
    img
}

fn reorder_img(img: Vec<u8>, parallel_encoding_units: usize, img_width: usize) -> Vec<u8> {
    // Testing if reordering is unnecessary
    if parallel_encoding_units == 1 || img_width == 1 { return img; }

    let chunk_size = parallel_encoding_units * img_width;

    let indices = (0..chunk_size)
        .map(|ind| {
            let position = (ind * parallel_encoding_units) % chunk_size;
            let offset = ind / img_width;
            position + offset
        })
        .collect::<Vec<usize>>();

    debug!("Mapping");
    reorder_by_mapping(img.clone(), indices.clone(), chunk_size.clone());
    debug!("Perm");
    reorder_by_perm(img.clone(), indices.clone(), chunk_size.clone());
    debug!("Perm mut");
    reorder_by_perm_mut(img.clone(), indices.clone(), chunk_size.clone())
}
```
</details>

**Comment by jeremysalwen** [comment]
Hi, your problem is that you are using `sort_unstable` which will actually *sort* the indices in O(nlogn) time, and then record the permutation that sorted them.  But you already have the indices calculated!  You can just use `oneline()` to construct a permutation from the indices directly.  Note that your indices are in the opposite notation of the oneline notation, so you will need to invert the constructed permutation to make it apply correctly.
