### ISSUE TITLE
crates.io update

### ISSUE THREAD

**Issue by joeftiger** [jeremysalwen/rust-permutations#7]
Hello

Thank you for this nice small library, it helps me sorting spectral representations.
I found that the current version of `crates.io` still relies on ordered types: `sort_by<T: Ord, ...>(...)` 
(https://docs.rs/permutation/0.2.5/permutation/permutation/fn.sort_by.html)

However, in the current source it has been fixed already. Could you update the public crate?
Thank you!

**Comment by jeremysalwen** [comment]
Done, with release 0.3.0 now on crates.io
